name: Test

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'

    - name: Install dependencies
      run: |
        export GO111MODULE=off
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin -d v1.39.0
        python -m pip install --upgrade pip semgrep
        go get github.com/vakenbolt/go-test-report
        go get golang.org/x/tools/cmd/cover

    - name: Run the default task
      run: |
        bin/test

    - name: Archive reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          test_report.html
          coverage_report.html
          semgrep-ci-report.xml
          semgrep-docker-report.xml
          semgrep-golang-report.xml
          semgrep-security-report.xml
